# Generated by Django 3.2.8 on 2026-02-15 10:35

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expert', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(default='No description provided.', help_text='A brief description or biography of the doctor.')),
                ('from_time', models.TimeField(default=datetime.time(9, 0), help_text='Available from time in 24hr format.')),
                ('to_time', models.TimeField(default=datetime.time(17, 0), help_text='Available until time in 24hr format.')),
            ],
        ),
    ]
