# Generated by Django 3.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_rename_doctors_doctor'),
        ('med', '0005_auto_20260215_1857'),
    ]

    operations = [
    ]