# Generated by Django 3.2.8 on 2026-02-15 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default=9999888822, max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
